name: GitHub CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 3.7
            runs:
              build: docker build --tag 'thontechnology/amazonlinux2-python:3.7.17' --tag 'thontechnology/amazonlinux2-python:3.7' '3.7'
              history: docker history 'thontechnology/amazonlinux2-python:3.7.17'
              pull: docker pull 'amazonlinux:2'
              push: docker push 'thontechnology/amazonlinux2-python:3.7.17' && docker push 'thontechnology/amazonlinux2-python:3.7'
          - name: 3.8
            runs:
              build: docker build --tag 'thontechnology/amazonlinux2-python:3.8.20' --tag 'thontechnology/amazonlinux2-python:3.8' '3.8'
              history: docker history 'thontechnology/amazonlinux2-python:3.8.20'
              pull: docker pull 'amazonlinux:2'
              push: docker push 'thontechnology/amazonlinux2-python:3.8.20' && docker push 'thontechnology/amazonlinux2-python:3.8'
          - name: 3.9
            runs:
              build: docker build --tag 'thontechnology/amazonlinux2-python:3.9.23' --tag 'thontechnology/amazonlinux2-python:3.9' '3.9'
              history: docker history 'thontechnology/amazonlinux2-python:3.9.23'
              pull: docker pull 'amazonlinux:2'
              push: docker push 'thontechnology/amazonlinux2-python:3.9.23' && docker push 'thontechnology/amazonlinux2-python:3.9'
          - name: 3.10
            runs:
              build: docker build --tag 'thontechnology/amazonlinux2-python:3.10.18' --tag 'thontechnology/amazonlinux2-python:3.10' '3.10'
              history: docker history 'thontechnology/amazonlinux2-python:3.10.18'
              pull: docker pull 'amazonlinux:2'
              push: docker push 'thontechnology/amazonlinux2-python:3.10.18' && docker push 'thontechnology/amazonlinux2-python:3.10'
          - name: 3.11
            runs:
              build: docker build --tag 'thontechnology/amazonlinux2-python:3.11.13' --tag 'thontechnology/amazonlinux2-python:3.11' --tag 'thontechnology/amazonlinux2-python:3' --tag 'thontechnology/amazonlinux2-python:latest' '3.11'
              history: docker history 'thontechnology/amazonlinux2-python:3.11.13'
              pull: docker pull 'amazonlinux:2'
              push: docker push 'thontechnology/amazonlinux2-python:3.11.13' && docker push 'thontechnology/amazonlinux2-python:3.11' && docker push 'thontechnology/amazonlinux2-python:3' && docker push 'thontechnology/amazonlinux2-python:latest'
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v1
      - name: Pull Dependencies
        run: ${{ matrix.runs.pull }}
      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}
      - name: Push ${{ matrix.name }}
        run: ${{ matrix.runs.push }}
      - name: History ${{ matrix.name }}
        run: ${{ matrix.runs.history }}
