name: GitHub CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 3.7
            runs:
              build: docker build --tag 'thontechnology/amazonlinux2-python:3.7.12' --tag 'thontechnology/amazonlinux2-python:3.7' '3.7.12'
              history: docker history 'thontechnology/amazonlinux2-python:3.7.12'
              pull: docker pull 'amazonlinux:2'
              images: docker image ls --filter since=image-list-marker
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v1
      - name: Pull Dependencies
        run: ${{ matrix.runs.pull }}
      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}
      - name: History ${{ matrix.name }}
        run: ${{ matrix.runs.history }}
      - name: '"docker images"'
        run: ${{ matrix.runs.images }}
      - name: Log out of DockerHub
        uses: docker/login-action@v1
        with:
          logout: true
