name: GitHub CI

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 3.7
            runs:
              build: docker build --tag 'penn-state-dance-marathon/amazonlinux2-python:3.7.12' --tag 'penn-state-dance-marathon/amazonlinux2-python:3.7' '3.7.12'
              history: docker history 'penn-state-dance-marathon/amazonlinux2-python:3.7.12'
              pull: docker pull 'penn-state-dance-marathon/amazonlinux2-python:3.7.12'
              images: docker image ls --filter since=image-list-marker
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pull Dependencies
        run: ${{ matrix.runs.pull }}
      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}
      - name: History ${{ matrix.name }}
        run: ${{ matrix.runs.history }}
      - name: '"docker images"'
        run: ${{ matrix.runs.images }}
