name: GitHub CI

on:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    needs: generate-jobs
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 3.7
            build: docker build --tag 'penn-state-dance-marathon/amazonlinux2-python:3.7.12' --tag 'penn-state-dance-marathon/amazonlinux2-python:3.7' '3.7.12'
            history: docker history 'penn-state-dance-marathon/amazonlinux2-python:3.7.12'
            prepare: git clone --depth 1 https://github.com/docker-library/official-images.git -b master ~/oi\n# create a dummy empty image/layer so we can --filter since= later to get a meaningful image list\n{ echo FROM busybox:latest; echo RUN :; } | docker build --no-cache --tag image-list-marker -\n# PGP Happy Eyeballs\ngit clone --depth 1 https://github.com/tianon/pgp-happy-eyeballs.git ~/phe\n~/phe/hack-my-builds.sh\nrm -rf ~/phe
            pull: docker pull 'penn-state-dance-marathon/amazonlinux2-python:3.7.12'
            images: docker image ls --filter since=image-list-marker
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Prepare Environment
        run: ${{ matrix.runs.prepare }}
      - name: Pull Dependencies
        run: ${{ matrix.runs.pull }}
      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}
      - name: History ${{ matrix.name }}
        run: ${{ matrix.runs.history }}
      - name: '"docker images"'
        run: ${{ matrix.runs.images }}
